import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { OUTPUT_DIR, readPublicStrings, renderModules } from '../../scripts/public-strings';
import * as STRINGS from '@/lib/i18n/strings';
import { PLACEHOLDER_KEYS } from '@/lib/i18n/format';
import { ACCESSORIES, ASSEMBLY_SERVICES, CATALOG_PRODUCTS, DELIVERY_METHODS, MODELS, USE_CASES } from '@/lib/data/seed-data';
import { CUSTOMER_ACCESSORY_IDS } from '@/components/configurator/AdvancedSettingsAccordion';
import { isModelSlugPubliclyVisible } from '@/lib/config/launch-visibility';

/**
 * docs/localization/public-strings.csv (owner-reviewed) → src/lib/i18n/strings
 * (generated by `npm run i18n:generate`, read at runtime). The CSV is never
 * parsed per request; these tests prove the generated dictionary IS the CSV.
 */

const rows = readPublicStrings();
const dictionary = Object.values(STRINGS).reduce<Record<string, { ru: string; kk: string }>>(
  (all, group) => Object.assign(all, group),
  {},
);

describe('generated dictionary', () => {
  it('is exactly what the generator produces from the current CSV (deterministic, not hand-edited)', () => {
    const expected = renderModules(rows);
    const onDisk = readdirSync(OUTPUT_DIR).sort();
    expect(onDisk).toEqual([...expected.keys()].sort());
    for (const [name, content] of expected) {
      expect(readFileSync(join(OUTPUT_DIR, name), 'utf8'), name).toBe(content);
    }
    // Generating twice yields the same bytes.
    expect([...renderModules(readPublicStrings()).values()]).toEqual([...expected.values()]);
  });

  it('carries every CSV row, ru_text and kk_proposed byte for byte', () => {
    expect(Object.keys(dictionary).sort()).toEqual(rows.map((r) => r.id).sort());
    for (const r of rows) {
      expect(dictionary[r.id].ru, r.id).toBe(r.ru_text);
      expect(dictionary[r.id].kk, r.id).toBe(r.kk_proposed);
    }
  });

  it('keeps the owner-approved punctuation "Сәлеметсіз бе ?!"', () => {
    for (const id of ['WA-001', 'WA-002', 'WA-003', 'WA-019']) {
      expect(dictionary[id].kk.startsWith('Сәлеметсіз бе ?!'), id).toBe(true);
    }
  });

  it('resolves every placeholder, and the ru and kk texts of a row ask for the same values', () => {
    const names = (text: string) => [...text.matchAll(/\{([^{}]+)\}/g)].map((m) => m[1]);
    for (const r of rows) {
      if (r.id === 'G-011') continue; // three Russian forms in one cell — rendered by shelvesLabel()
      const ru = names(r.ru_text).map((n) => PLACEHOLDER_KEYS[n]);
      const kk = names(r.kk_proposed).map((n) => PLACEHOLDER_KEYS[n]);
      expect(ru.every(Boolean) && kk.every(Boolean), `${r.id}: unknown placeholder`).toBe(true);
      expect([...new Set(kk)].sort(), r.id).toEqual([...new Set(ru)].sort());
    }
  });
});

describe('authoritative business wording', () => {
  it('delivery, non-standard sizes and the configurator hint are the approved texts', () => {
    expect(dictionary['CF-087']).toEqual({
      ru: 'Доставка по Алматы, Астане, Караганде и Шымкенту — бесплатно, в тот же день.',
      kk: 'Алматы, Астана, Қарағанды және Шымкент қалаларында жеткізу — тегін, сол күні.',
    });
    expect(dictionary['CF-089']).toEqual({
      ru: 'Доставка в другие города и регионы Казахстана — 2–3 дня. Стоимость доставки рассчитывается индивидуально.',
      kk: 'Қазақстанның басқа қалалары мен өңірлеріне жеткізу — 2–3 күн. Жеткізу құны жеке есептеледі.',
    });
    expect(dictionary['FQ-005']).toEqual({
      ru: 'Нет. Доступны только размеры, представленные в конфигураторе.',
      kk: 'Жоқ. Тек конфигураторда көрсетілген өлшемдер қолжетімді.',
    });
    expect(dictionary['CF-021'].ru).toContain('точки изменения размера');
  });
});

describe('catalogue data (Prisma *Kk columns / seed-data) matches the owner-reviewed Kazakh', () => {
  const byRu = new Map<string, string[]>();
  for (const r of rows) byRu.set(r.ru_text, [...(byRu.get(r.ru_text) ?? []), r.kk_proposed]);

  const publicTexts: (readonly [string, { ru: string; kk: string }])[] = [
    ...DELIVERY_METHODS.filter((d) => d.active).flatMap((d) => [[`delivery ${d.id}`, d.name], [`delivery ${d.id} description`, d.description]] as const),
    ...ASSEMBLY_SERVICES.filter((s) => s.active).flatMap((s) => [[`assembly ${s.id}`, s.name], [`assembly ${s.id} description`, s.description]] as const),
    ...ACCESSORIES.filter((a) => (CUSTOMER_ACCESSORY_IDS as readonly string[]).includes(a.id)).map((a) => [`accessory ${a.id}`, a.name] as const),
    ...MODELS.filter((m) => isModelSlugPubliclyVisible(m.slug)).flatMap((m) => [
      [`model ${m.slug}`, m.name] as const,
      [`model ${m.slug} short`, m.shortDescription] as const,
      [`model ${m.slug} description`, m.description] as const,
    ]),
    ...CATALOG_PRODUCTS.filter((p) => p.published && isModelSlugPubliclyVisible(p.modelSlug)).flatMap((p) => [
      [`product ${p.slug}`, p.name] as const,
      [`product ${p.slug} description`, p.description] as const,
    ]),
    ...USE_CASES.map((u) => [`use case ${u.id}`, u] as const),
  ];

  it.each(publicTexts)('%s', (_, text) => {
    expect(byRu.has(text.ru), `no CSV row for "${text.ru}"`).toBe(true);
    expect(byRu.get(text.ru)).toContain(text.kk);
  });
});
